VoxelDownsample:
  x_range: [-40.0, 40.0]
  y_range: [-40.0, 40.0]
  z_range: [-1.0,3.0]
  voxel_size:
    x: 0.2
    y: 0.2
    z: 0.2

GNNLayers:
  - name: GNN_layer_1
    mlp_h:
      dim_lst: [64, 64]
      activation: relu
      output_activation: none
    mlp_f:
      feat_dim: 32
      hidden_dim_lst: [32, 32]
      activation: relu
      output_activation: none
    mlp_g:
      dim_lst: [64, 64]
      activation: relu
      output_activation: none
  - name: GNN_layer_2
    mlp_h:
      dim_lst: [64, 64]
      activation: relu
      output_activation: none
    mlp_f:
      feat_dim: 32
      hidden_dim_lst: [32, 32]
      activation: relu
      output_activation: none
    mlp_g:
      dim_lst: [64, 64]
      activation: relu
      output_activation: none

ClassificationHead:
  mlp:
    dim_lst: [64, 64, 3] # 3 classes, vehicle and human and background
    activation: relu
    output_activation: none

LocalizationHead: # regress bounding boxes, one head for each foreground class
  - vehicles:
      mlp:
        dim_lst: [64, 64, 7] # 7 delta values for x, y, z, l, w, h, theta
        activation: relu
        output_activation: none
  - human:
      mlp:
        dim_lst: [64, 64, 7] # 7 delta values for x, y, z, l, w, h, theta
        activation: relu
        output_activation: none

Dataset:
  nuscenes:
    filepath: /home/ji-liu/Robotics/NuScenes/NuScenes_mini
    version: v1.0-mini
    num_classes: 6

AnchorBox:
  - class: vehicle.car
    wlh: [1.9,4.6,1.7]
  - class: vehicle.truck
    wlh: [2.4,6.5,2.6]
  - class: vehicle.bus
    wlh: [2.9,10.0,3.5]
  - class: vehicle.construction
    wlh: [2.6,5.6,2.4]
  - class: vehicle.bicycle
    wlh: [0.6,1.8,1.4]
  - class: vehicle.motorcycle
    wlh: [0.68, 1.95, 1.47]
  - class: vehicle.trailer
    wlh: [2.3,10.0,3.7]