model:
  name: point_gnn
  module_default: # stores anchors for repeated use
    point_feat_dim: &point_feat_dim 256
    edge_feat_dim: &edge_feat_dim 256
    point_gnn_default: &point_gnn_default
      mlp_h:
        inp_dim: *point_feat_dim
        hidden_dim_lst: [64,16]
        out_dim: 3 # has to be 3 for delta pos
        activation: relu
        output_activation: none
        add_batch_norm: true
      mlp_f:
        inp_dim : *point_feat_dim # dim of 3 for pos offset is added in the model init
        hidden_dim_lst : [256]
        out_dim : *edge_feat_dim
        activation : relu
        output_activation : none
        add_batch_norm : true
      mlp_g:
        inp_dim: *edge_feat_dim
        hidden_dim_lst: [256]
        out_dim: *point_feat_dim
        activation: relu
        output_activation: none
        add_batch_norm: true
  modules:
    - name: entry
      inp_src:
        - &x args:0 # x
        - &pos args:1 # pos
        - &edge_index args:2 # edge_index
    - name: point_net_encoder
      cls: point_net_encoder
      inp_src:
        - *x
        - *pos 
        - *edge_index
      config:
        out_varname: x
        local_nn: # mlp
          inp_dim: 1 # initial lidar feature dim (reflectance) is 1. dim of 3 for pos is added in the model init
          hidden_dim_lst: [4,16,64]
          out_dim: &local_nn_dout 256
          activation: relu
          output_activation: none
          add_batch_norm: True
        global_nn: # mlp
          inp_dim: *local_nn_dout
          hidden_dim_lst: [256,256]
          out_dim: *point_feat_dim
          activation: relu
          output_activation: none
          add_batch_norm: True
    - name: point_gnn_l1
      cls: point_gnn_layer
      inp_src: 
        - point_net_encoder:x
        - *pos
        - *edge_index
      config:
        out_varname: x
        <<: *point_gnn_default
    - name: point_gnn_l2
      cls: point_gnn_layer
      inp_src: 
        - point_gnn_l1:x
        - *pos
        - *edge_index
      config: 
        out_varname: x
        <<: *point_gnn_default
    - name: point_gnn_l3
      cls: point_gnn_layer
      inp_src: 
        - point_gnn_l2:x
        - *pos
        - *edge_index
      config: 
        out_varname: x
        <<: *point_gnn_default
    - name: shared_mlp
      cls: mlp
      inp_src:
        - point_gnn_l3:x
      config:
        out_varname: x
        inp_dim: *point_feat_dim
        hidden_dim_lst: [256,256]
        out_dim: &shared_dout 256
        activation: relu
        output_activation: relu
        add_batch_norm: true
    - name: background_class_head
      cls: background_class_head
      inp_src:
        - shared_mlp:x
      config:
        out_varname: x
        inp_dim: *shared_dout
        hidden_dim_lst: [128,64]
        out_dim: 2
        activation: relu
        output_activation: none
        add_batch_norm: True
        output_format: log_softmax
    - name: object_class_head
      cls: object_class_head
      inp_src:
        - shared_mlp:x
      config:
        out_varname: x
        inp_dim: *shared_dout
        hidden_dim_lst: [128,64]
        out_dim: 7 # num of classes [car, truck, bus, construction, bicycle, motorcycle, trailor]
        activation: relu
        output_activation: none
        add_batch_norm: True
        output_format: log_softmax
    - name: box_size_head
      cls: box_size_head
      inp_src:
        - shared_mlp:x
      config:
        out_varname: x
        inp_dim: *shared_dout
        hidden_dim_lst: [128,64]
        out_dim: 3
        activation: relu
        output_activation: relu
        add_batch_norm: True
    - name: localization_head
      cls: localization_head
      inp_src:
        - point_gnn_l3:x
      config:
        out_varname: x
        inp_dim: *point_feat_dim
        hidden_dim_lst: [256,256]
        out_dim: 3 # only for delta x,y,z
        activation: relu
        output_activation: none
        add_batch_norm: True
    - name: orientation_head
      cls: orientation_head
      inp_src:
        - point_gnn_l3:x
      config:
        out_varname: x
        inp_dim: *point_feat_dim
        hidden_dim_lst: [128,64]
        out_dim: 1
        activation: relu
        output_activation: none
        add_batch_norm: True
        clip_output: [-1., 1.]
    - name: exit
      inp_src:
        background: background_class_head:x
        object: object_class_head:x
        localization: localization_head:x
        box_size: box_size_head:x
        orientation: orientation_head:x

loss:
  name: loss
  unpack_sequence:
    - background
    - object
    - localization
    - box_size
    - orientation
    - mask
  modules:
    - name: entry
      inp_src:
        - &background_pred args:0
        - &background_target args:1
        - &object_pred args:2
        - &object_target args:3
        - &localization_pred args:4
        - &localization_target args:5
        - &box_size_pred args:6
        - &box_size_target args:7
        - &orientation_pred args:8
        - &orientation_target args:9
        - &mask args:10
    - name: background_loss
      cls: nll_loss
      inp_src:
        - *background_pred
        - *background_target
      config:
        out_varname: loss
        weight: [0.5, 1.0] # [background, object]
        reduction: mean
    - name: object_loss
      cls: nll_loss
      inp_src:
        - *object_pred
        - *object_target
        - *mask
      config:
        out_varname: loss
        weight:
          - 1.0 # car
          - 1.0 # truck
          - 1.0 # bus
          - 1.0 # construction
          - 1.0 # bicycle
          - 1.0 # motorcycle
          - 1.0 # trailor
        reduction: custom
    - name: localization_loss
      cls: huber_loss
      inp_src:
        - *localization_pred
        - *localization_target
        - *mask
      config:
        out_varname: loss
        delta: 1.0
        reduction: custom
    - name: box_size_loss
      cls: huber_loss
      inp_src:
        - *box_size_pred
        - *box_size_target
        - *mask
      config:
        out_varname: loss
        delta: 1.0
        reduction: custom
    - name: orientation_loss
      cls: huber_loss
      inp_src:
        - *orientation_pred
        - *orientation_target
        - *mask
      config:
        out_varname: loss
        delta: 1.0
        reduction: custom
    - name: total_loss
      cls: total_loss
      inp_src:
        - background_loss:loss
        - object_loss:loss
        - localization_loss:loss
        - box_size_loss:loss
        - orientation_loss:loss
      config:
        out_varname: loss
        loss_coef:
          - 1.0 # background
          - 0.5 # object
          - 2.0 # localization
          - 2.0 # box_size
          - 2.0 # orientation
    - name: exit
      inp_src:
        total: "total_loss:loss"
        background: "background_loss:loss"
        object: "object_loss:loss"
        localization: "localization_loss:loss"
        box_size: "box_size_loss:loss"
        orientation: "orientation_loss:loss"