batch_size: 2
epochs: 100
dataloader:
  train:
    shuffle: true
  val:
    shuffle: false
  test:
    shuffle: false
torch_dynamo: true
logging_dir : ./runs
target_loss_name: total
optimizer:
  name: adam
  config:
    lr: 0.001
    weight_decay: 0.00001
    betas: [0.9, 0.999]
    eps: 1.0e-8
    amsgrad: False
scheduler:
  name: plateau
  config:
    mode: min
    factor: 0.5
    patience: 5
    threshold: 0.01
    threshold_mode: rel
    cooldown: 0
    min_lr: 1.0e-6